// external.js

function showExternalMessage() {
  document.getElementById("message-area").textContent = "This message is generated by external JavaScript!";
  console.log("External JavaScript button clicked.");
}